version: "3"

services:
  product-service1:
    build: ./pythonproduct
    volumes:
      - ./pythonproduct:/usr/src/app
    ports:
      - 5001:80

  website1:
    image: php:7-apache
    volumes:
      - ./productphp:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service1
